# server/src/config/risk.factors.yaml
#
# Per-symbol factor costs (lambda) and width parameters.
# You can hot-reload by restarting the server.
BTC:
  lambda: [0.50, 0.20, 0.10, 0.15, 0.10, 0.30]   # [L0, S0, C0, Sneg, Spos, F]
  widths:
    w0: 2.0      # base width in USD
    alpha: 1.0   # scales with |dot(lambda, g_i)|
    beta: 0.0    # reserved for inventory penalty routing
ETH:
  lambda: [0.40, 0.18, 0.09, 0.12, 0.09, 0.25]
  widths:
    w0: 1.2
    alpha: 0.9
    beta: 0.0
