name: CI - Vol Surface Validation

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  vol-validation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          npm ci
          pip install -r vol-core-validation/requirements.txt
      
      - name: Typecheck
        run: npm run typecheck
      
      - name: Generate fixtures
        run: npm run fixtures:python
      
      - name: Unit Wall (Golden Parity)
        run: npm run test:golden
      
      - name: No-Arb Guards
        run: npm run test:noarb
      
      - name: Upload diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics
          path: diagnostics/*.json
          retention-days: 30
