name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - 'ai/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Install deps (pnpm preferred; fallback to npm)
        run: |
          if [ -f pnpm-lock.yaml ]; then
            corepack prepare pnpm@latest --activate
            pnpm install --frozen-lockfile
          else
            npm ci
          fi

      - name: Typecheck (best-effort)
        run: |
          npm run -s typecheck || echo "typecheck skipped/failed (non-blocking)"
          if command -v pnpm >/dev/null 2>&1; then pnpm -s typecheck || true; fi

      - name: Lint (best-effort)
        run: |
          npm run -s lint || echo "lint skipped/failed (non-blocking)"
          if command -v pnpm >/dev/null 2>&1; then pnpm -s lint || true; fi

      - name: Tests
        run: |
          npm test --silent --if-present -- --ci || echo "npm tests absent or failing"
          if command -v pnpm >/dev/null 2>&1; then pnpm -s test --if-present -- --ci || true; fi

      - name: Build (optional)
        run: |
          npm run -s build --if-present || echo "build step not defined"
          if command -v pnpm >/dev/null 2>&1; then pnpm -s build --if-present || true; fi
